#! /bin/sh

#░█▀▄░█▀▀░█▀█░█░█░█▄█
#░█▀▄░▀▀█░█▀▀░█▄█░█░█
#░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀

#bspc monitor -d 1 2 3 4 5 6 # 7 8 9 10
bspc monitor LVDS-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 0

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config focus_follows_pointer false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config swallow_first_click false
bspc config pointer_modifier mod1
#bspc config pointer_action1 resize_side
#bspc config pointer_action1 resize_corner
#bspc config pointer_action3 move
bspc config normal_border_color "#282828"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#77dd77"
bspc config presel_feedback_color "#BF616A"
#bspc config normal_border_color "#282828"
#bspc config active_border_color "#ebdbb2"
#bspc config focused_border_color "#fe8019"

# remove all rules first
bspc rule -r *:*

bspc rule -a Plank layer=above border=off

###---Autostart---####
pgrep -x sxhkd >/dev/null || sxhkd &
picom -b --experimental-backends &
if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
    xrandr --output LVDS-1 --primary --mode 1366x768 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --right-of LVDS-1
fi
xfce4-panel --disable-wm-check &
"$HOME"/.config/polybar/launch.sh &

feh --bg-fill "$HOME"/pictures/wallpapers/national-park.jpg
dunst &     # notification daemon
unclutter & # Remove mouse when idle
#nitrogen --force-setter=xinerama --restore &
#bspc rule -a \* rectangle=680x700+340+40
bspc rule -a '*:*:Picture-in-Picture' state=floating sticky=on layer=above
bspc rule -a '*:*:Picture in picture' state=floating sticky=on layer=above
bspc rule -a firefox:Toolkit focus=on state=floating sticky=on layer=above rectangle=522x320+830+280
#320x190+1030+480
#522x316-10+280
bspc rule -a "https://www.youtube.com - Enhancer for YouTube™ — Mozilla Firefox" state=floating sticky=on layer=above
bspc rule -a Wezterm state=floating
bspc rule -a Zathura state=tiled

# SCRATCHPAD
bspc rule -a scratchpad sticky=on state=floating

# Heads Up Display (scratchpad)
bspc rule -a Heads-Up-Display sticky=on state=floating rectangle=360x160+990+40

[ "$1" = 0 ] && {
    nm-applet &
    plank &
}

pkill xfce4-power-manager
sleep 1 && nice -n 1 xfce4-power-manager &
pkill volumeicon
sleep 2 && nice -n 2 volumeicon &
pkill mictray
sleep 2 && nice -n 2 mictray &
pkill parcellite
sleep 2 && nice -n 2 parcellite &
pkill udiskie
sleep 2 && nice -n 2 udiskie &

pkill eww
eww daemon
#"$(which eww)" -c "$HOME"/.config/eww --restart open dock &

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [ "$state" != "fullscreen" ]; then
        continue
    fi
    if [ "$flag" == on ]; then
        "$(which eww)" -c "$HOME"/.config/eww close-all
    else
        "$(which eww)" -c "$HOME"/.config/eww open bar
    fi
done &

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [[ "$state" != fullscreen ]]; then continue; fi
    if [[ "$flag" == on ]]; then
        xdo lower -N Plank
    else
        xdo raise -N Plank
    fi
done &

bspc config external_rules_command ~/.config/bspwm/scripts/external_rules.sh
